name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        libgccjit_version:
          - { gcc: "gcc-15.deb" }
          - { gcc: "gcc-15-without-int128.deb" }

    steps:
    - uses: actions/checkout@v4

    - name: Print artifact
      run: echo ${{ matrix.libgccjit_version.gcc }}

  duplicates:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: echo Duplicates
