name: CI libgccjit 12

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-24.04

    strategy:
      fail-fast: false
      matrix:
        commands: [
          "--mini-tests",
          "--std-tests",
        ]

    steps:
    - uses: actions/checkout@v4

    - name: Run tests
      run: echo Running ${{ matrix.commands }}
