name: Required checks

on:
  - pull_request

jobs:
  required-checks:
    runs-on: ubuntu-latest
    steps:
    - name: Wait for required checks
      uses: roryq/required-checks@master
      with:
        required_workflow_patterns: |
          - build
